demo/JRASP/JRASP/urls.py
from django.conf.urls import patterns, include, url
from django.views.static import *
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'index.views.index', name='idx'),
    url(r'^guideline/$', 'index.views.author_guideline', name='author_guideline'),
    (r'^users/', include('users.urls')),
    (r'^article/', include('article.urls')),
    (r'^util/', include('util.urls')),
    (r'^add_article/', include('add_article.urls')),

    # url(r'^$', 'JRASP.views.home', name='home'),
    # url(r'^JRASP/', include('JRASP.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
		(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

demo/JRASP/article/urls.py
from django.conf.urls.defaults import *
from django.views.static import *
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('article.views',
    url(r'^$', 'articles',name='articles'),	
    url(r'^add_comment/$', 'add_comment',name='add_comment'),	
	url(r'^(?P<id_article>\w+)/$', 'article',name='article'),	
    
)

demo/JRASP/util/urls.py
from django.conf.urls.defaults import *
from django.views.static import *
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('util.views',
					   
    url(r'^download/(?P<file>\w+)/$', 'download', name='download'),		   
    url(r'^autoKW/(?P<key>\w+)/$', 'autoKW', name='autoKW'),
)

demo/JRASP/JRASP/models.py
# -*- coding: utf-8 -*-

# Here's the models for the new database !
# Very useful and very easy to use
# not like the former one, extracted from the Slim's one
import os
from django.db import models

class KW(models.Model):
	id_kw = models.AutoField(primary_key=True)
	nm_kw = models.CharField(max_length=500)
	class Meta:
		db_table = u'kw'
	def __unicode__(self):
		return self.nm_kw

class Skill(models.Model):
	id_skill = models.AutoField(primary_key=True)
	name_skill = models.CharField(max_length = 200)
	class Meta:
		db_table = u'skill'
	def __unicode__(self):
		return self.name_skill
	@property
	def get_skill_rate(self):
		usk = self.userskill_set.all()
		return usk[0].rate
		

class User(models.Model):
	id_user = models.AutoField( primary_key = True )
	name_user = models.CharField(max_length = 200)
	fst_name_user = models.CharField(max_length = 200)
	skill_user = models.ManyToManyField(Skill, through='UserSkill',null=True,blank=True)
	class Meta:
		db_table = u'user'
	def __unicode__(self):
		return unicode(self.fst_name_user+' '+self.name_user)
	def get_user_skills(self):
		return self.skill_user

class UserSkill(models.Model):
	id = models.AutoField(primary_key = True)
	user = models.ForeignKey(User)
	skill = models.ForeignKey(Skill)
	rate = models.IntegerField(default=0)
	class Meta:
		db_table = u'user_s_skill'
		
class File(models.Model):
	id_file = models.AutoField(primary_key=True)
	nm_file = models.CharField(max_length = 2000)
	url_file= models.CharField(max_length = 20000)
	size = models.IntegerField(null=True,blank=True)
	type_file = models.CharField(max_length = 200)
	date_creation_file = models.DateField()
	date_modification_file = models.DateField()
	number_download = models.IntegerField(default=0)
	class Meta:
		db_table = u'file'


class Article(models.Model):
	id_article = models.AutoField(primary_key=True)
	title = models.CharField(max_length = 2000)
	author = models.CharField(max_length = 5000) #contains just a string for uthor and affiliation
	reviewer = models.ManyToManyField(User, db_table='article_reviewer', related_name='article_reviewers',null=True,blank=True)
	abstract = models.CharField(max_length = 500000)
	KW = models.ManyToManyField(KW,db_table='article_kw',null=True,blank=True)
	pdf = models.ForeignKey(File,related_name='article_pdf')
	code = models.ForeignKey(File,related_name='article_code')
	example = models.CharField(max_length = 500000)
	date = models.DateField()
	views = models.IntegerField(default=0)
	class Meta:
		db_table = u'article'
		ordering = ['date']


class Feedback(models.Model):
	id_feedback = models.AutoField(primary_key=True)
	title_feedback = models.CharField(max_length = 2000)
	author = models.CharField(max_length = 2000)
	slug = models.CharField(max_length = 500000)
	date_publication = models.DateField()
	good_comment = models.IntegerField(default=0)
	article = models.ForeignKey(Article)
	class Meta:
		db_table = u'feedback'
		ordering = ['good_comment']

demo/JRASP/article/models.py
from django.db import models

# Create your models here.

demo/JRASP/article/views.py
# Create your views here.
from django.shortcuts import render_to_response, get_object_or_404, redirect, HttpResponseRedirect, HttpResponse
from django import forms
from django.template import RequestContext

from JRASP.models import *
from JRASP.forms import FeedbackForm

import datetime

def articles(request):
	"""
	Show all the articles into some fancy way 
	"""
	articles = Article.objects.all()
	return render_to_response('article/articles.html',{'articles': articles,}, context_instance=RequestContext(request))


def article(request, id_article):
	"""
	Show all the information about an article
	id_article : as the name indicates, it is the id of the article you want to see
	"""
	article = get_object_or_404(Article, id_article = id_article)
	article.views = article.views + 1
	article.save()
	if request.method=='POST': #a comment is send
		form = FeedbackForm(request.POST)
		if form.is_valid():
			date= datetime.date.today()
			fb = Feedback(title_feedback = form.cleaned_data['title'], author = form.cleaned_data['author'], slug=form.cleaned_data['slug'],date_publication=date,article=article)
			fb.save()
		else:
			#error
			return render_to_response('article/article.html',{'article': article,'form':form,'error_message':form.errors }, context_instance=RequestContext(request))
	
	# the usual way to show this page 
	form = FeedbackForm()
	return render_to_response('article/article.html',{'article': article,'form':form}, context_instance=RequestContext(request))

def add_comment(request):
	"""
	just count the good comment of a feedback
	"""
	html=""
	if request.GET.has_key('id_fb'):
		id_fb = int(request.GET['id_fb'])
		fb = get_object_or_404(Feedback,id_feedback=id_fb)
		fb.good_comment = fb.good_comment + 1
		fb.save()
		html=unicode(fb.good_comment)
	return HttpResponse(html)
	

demo/templates/article/article.html
{% extends 'base.html' %}

{% block head_title %} J-RASP article {% endblock %}
{% block head_js %} 
<script type="text/javascript" src="/users/static/js/view.js"></script> 
<script type="text/javascript" src="/users/static/js/prototype.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js"></script>
{% endblock %}
{% block content %}



{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}

<div class="block_rasp">

  <h1>{{article.title}}</h1>
  {{article.author}}

  <div class="bsubblock">
	<h3> Abstract </h3>
	{{article.abstract}}
	<br>
	{% for kw in article.KW.all %}<a href="#"> <!-- will be KW search in the futur -->{{kw}}, </a>{% endfor %}
	<br>
	This article was read {{article.views}} times 
  </div>

  <div class="bsubblock">
	<h3> Downloadable content </h3>
	<a href="{% url 'download' article.pdf.id_file %}">[PDF]</a>   <a href="{% url 'download' article.code.id_file%}"> [SOURCE CODE] </a><br> 
	code downloaded {{article.code.number_download}} times
  </div>


  <div class="bsubblock">
	<h3>Examples</h3>
	{{article.example|safe}}
  </div>

  <div class="bsubblock">
	<h3> Feedback </h3>
	{% for fb in article.feedback_set.all%}
	<div class="feedback">
	  <!-- do a TABLE GOBSHIT ! -->
	  <div class="author_feedback">
		Author : <i> {{fb.author}}</i><br>
		Date : {{fb.date_publication}}
	  </div>
	  <div class="core_feedback">
		<h4>{{fb.title_feedback}}</h4>
		<p>
		  {{fb.slug}}
		</p>
		<div id="good_comment_{{fb.id_feedback}}">
		  {{fb.good_comment}} <input type="button" href="#" onclick="add_good_comment({{fb.id_feedback}})" value="Thumb up" />
		</div>
		<!-- Here put a javascript function that count the good comment -->
	  </div>
	</div>
	{% endfor %}

	  <form action="{% url 'article' article.id_article%}" enctype="multipart/form-data" method="post"> {% csrf_token %}
		<table align="center">
		  {{form.as_table}}
		</table>
		<p align="center"> <input type="submit" value="Validate"/> </p>
	  </form>

  </div>


  {% endblock %}

demo/templates/article/articles.html
{% extends 'base.html' %}

{% block head_title %} J-RASP guideline {% endblock %}

{% block content %}



{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
<div class="block_rasp">
{% for a in articles %}

<a href="{% url 'article' a.id_article %}"> {{a.title}} </a>
{% endfor %}


</div>


{% endblock %}